command: ["streamlit", "run", "app.py"]

env:
  - name: "LAKEBASE_HOST"
    value: "ep-snowy-lake-d89m03dj.database.us-east-2.cloud.databricks.com"
  - name: "LAKEBASE_PORT"
    value: "5432"
  - name: "LAKEBASE_DB"
    value: "databricks_postgres"
  - name: "LAKEBASE_USER"
    value: "db_user_test"
  - name: "LAKEBASE_PASSWORD"
    valueFrom:
      secretKeyRef:
        scope: "ticket-tracker-secrets"
        key: "lakebase-password"
