command: ["streamlit", "run", "app.py"]

env:
  - name: "LAKEBASE_HOST"
    valueFrom: lakebase_host_secret
  - name: "LAKEBASE_PORT"
    value: "5432"
  - name: "LAKEBASE_DB"
    valueFrom: lakebase_db_secret
  - name: "LAKEBASE_USER"
    valueFrom: lakebase_user_secret
  - name: "LAKEBASE_PASSWORD"
    valueFrom: lakebase_password_secret
